import indiaSvgMap from "@svg-maps/india";

export type TimeframeMode = "live" | "week" | "month" | "annual";
export type MetricType = "total" | "urgent" | "saathi" | "helpline" | "resolution";

export type StateMetricPeriod = {
  totalCases: number;
  urgentCases: number;
  saathiCases: number;
  helplineCalls: number;
  resolutionRate: number; // percentage (e.g., 88)
  avgResponseMins: number; // minutes
};

export type DistrictData = {
  name: string;
  totalCases: number;
  urgentCases: number;
  counsellors: number;
  resolutionRate: number;
  trend: "up" | "down" | "stable";
};

export type DetailedStateData = {
  id: string; // lowercase code e.g. "up", "mh"
  code: string; // uppercase short code e.g. "UP", "MH"
  name: string;
  capital: string;
  region: "North" | "South" | "East" | "West" | "Central" | "North-East" | "Islands";
  riskLevel: "Critical" | "High" | "Moderate" | "Low";
  nodalOfficer: string;
  nodalPhone: string;
  helpline181Active: boolean;
  activeFlyingSquads: number;
  center: { x: number; y: number };
  bounds: { minX: number; maxX: number; minY: number; maxY: number; width: number; height: number };
  periods: {
    live: StateMetricPeriod;
    week: StateMetricPeriod;
    month: StateMetricPeriod;
    annual: StateMetricPeriod;
  };
  districts: DistrictData[];
};

export type HotspotIncidentPin = {
  id: string;
  name: string;
  stateId: string;
  x: number;
  y: number;
  activeResponders: number;
  incidentType: string;
  severity: "urgent" | "high" | "moderate";
  lastCallAgo: string;
};

export const regionViewBoxes: Record<string, { viewBox: string; label: string }> = {
  All: { viewBox: "0 0 612 696", label: "All India View" },
  North: { viewBox: "75 0 320 320", label: "North Zone (J&K, HP, PB, HR, DL, UK, UP)" },
  South: { viewBox: "100 400 270 290", label: "South Zone (KA, AP, TG, TN, KL)" },
  East: { viewBox: "280 200 270 240", label: "East Zone (BR, JH, WB, OR)" },
  West: { viewBox: "0 230 260 280", label: "West Zone (RJ, GJ, MH, GA)" },
  Central: { viewBox: "120 230 240 230", label: "Central Zone (MP, CG)" },
  "North-East": { viewBox: "420 180 190 190", label: "North-East Zone (Seven Sisters & SK)" },
};

export const indiaHotspots: HotspotIncidentPin[] = [
  {
    id: "h-dl",
    name: "Delhi NCR Command Cell",
    stateId: "dl",
    x: 186,
    y: 210,
    activeResponders: 24,
    incidentType: "Emergency SOS Escalation & Safe House Dispatch",
    severity: "urgent",
    lastCallAgo: "1m ago",
  },
  {
    id: "h-mum",
    name: "Mumbai Metropolitan Rapid Wing",
    stateId: "mh",
    x: 106,
    y: 422,
    activeResponders: 28,
    incidentType: "Immediate High-Risk Protection Intervention",
    severity: "urgent",
    lastCallAgo: "3m ago",
  },
  {
    id: "h-pune",
    name: "Pune Urban Distress Desk",
    stateId: "mh",
    x: 130,
    y: 445,
    activeResponders: 16,
    incidentType: "Silent In-App Emergency Flagged",
    severity: "high",
    lastCallAgo: "7m ago",
  },
  {
    id: "h-blr",
    name: "Bengaluru Tech Hub Intervention",
    stateId: "ka",
    x: 175,
    y: 545,
    activeResponders: 19,
    incidentType: "Workplace & Cyber Harassment Legal Aid",
    severity: "high",
    lastCallAgo: "4m ago",
  },
  {
    id: "h-hyd",
    name: "Hyderabad Cyberabad Flying Squad",
    stateId: "tg",
    x: 235,
    y: 465,
    activeResponders: 17,
    incidentType: "Psychological First Aid & Handoff",
    severity: "high",
    lastCallAgo: "9m ago",
  },
  {
    id: "h-kol",
    name: "Kolkata City Rapid Unit",
    stateId: "wb",
    x: 420,
    y: 320,
    activeResponders: 18,
    incidentType: "Tele-MANAS Inbound Call Transfer",
    severity: "urgent",
    lastCallAgo: "5m ago",
  },
  {
    id: "h-lko",
    name: "Lucknow Central Crisis Bureau",
    stateId: "up",
    x: 275,
    y: 240,
    activeResponders: 26,
    incidentType: "Domestic Violence 181 Multi-District Dispatch",
    severity: "urgent",
    lastCallAgo: "2m ago",
  },
  {
    id: "h-jpr",
    name: "Jaipur Regional Crisis Cell",
    stateId: "rj",
    x: 145,
    y: 235,
    activeResponders: 15,
    incidentType: "Rural Outreach Mobile Shelter Unit",
    severity: "urgent",
    lastCallAgo: "8m ago",
  },
  {
    id: "h-amd",
    name: "Ahmedabad Emergency Response Wing",
    stateId: "gj",
    x: 85,
    y: 345,
    activeResponders: 14,
    incidentType: "One-Stop Centre (OSC) Interlinkage",
    severity: "moderate",
    lastCallAgo: "12m ago",
  },
  {
    id: "h-pat",
    name: "Patna Gangetic Nodal Squad",
    stateId: "br",
    x: 375,
    y: 265,
    activeResponders: 15,
    incidentType: "Safe Transit & DLSA Legal Counsel",
    severity: "high",
    lastCallAgo: "6m ago",
  },
  {
    id: "h-gau",
    name: "Guwahati Eastern Hub",
    stateId: "as",
    x: 500,
    y: 275,
    activeResponders: 11,
    incidentType: "Cross-Border Vulnerability Hotline",
    severity: "moderate",
    lastCallAgo: "15m ago",
  },
  {
    id: "h-che",
    name: "Chennai Coastal Crisis Taskforce",
    stateId: "tn",
    x: 230,
    y: 560,
    activeResponders: 16,
    incidentType: "24x7 Women Helpline Escort Unit",
    severity: "moderate",
    lastCallAgo: "11m ago",
  },
];

// Complete 36 States and Union Territories with granular periods, districts, and official nodal references
export const detailedStatesMap: Record<string, DetailedStateData> = {
  up: {
    id: "up",
    code: "UP",
    name: "Uttar Pradesh",
    capital: "Lucknow",
    region: "North",
    riskLevel: "Critical",
    nodalOfficer: "Dr. Sunita Srivastava, IAS (State Women Cell)",
    nodalPhone: "0522-2238411 / 181",
    helpline181Active: true,
    activeFlyingSquads: 18,
    center: { x: 265, y: 245 },
    bounds: { minX: 186, maxX: 344, minY: 168, maxY: 322, width: 158, height: 154 },
    periods: {
      live: { totalCases: 284, urgentCases: 48, saathiCases: 38, helplineCalls: 412, resolutionRate: 79, avgResponseMins: 14 },
      week: { totalCases: 1940, urgentCases: 310, saathiCases: 245, helplineCalls: 2890, resolutionRate: 82, avgResponseMins: 18 },
      month: { totalCases: 7650, urgentCases: 1280, saathiCases: 940, helplineCalls: 11200, resolutionRate: 85, avgResponseMins: 22 },
      annual: { totalCases: 49385, urgentCases: 8420, saathiCases: 4420, helplineCalls: 68900, resolutionRate: 87, avgResponseMins: 25 },
    },
    districts: [
      { name: "Lucknow", totalCases: 6420, urgentCases: 1120, counsellors: 32, resolutionRate: 91, trend: "down" },
      { name: "Kanpur Nagar", totalCases: 5180, urgentCases: 890, counsellors: 24, resolutionRate: 86, trend: "stable" },
      { name: "Varanasi", totalCases: 4210, urgentCases: 710, counsellors: 19, resolutionRate: 89, trend: "down" },
      { name: "Agra", totalCases: 3890, urgentCases: 640, counsellors: 18, resolutionRate: 84, trend: "up" },
      { name: "Prayagraj", totalCases: 3740, urgentCases: 590, counsellors: 16, resolutionRate: 88, trend: "stable" },
      { name: "Ghaziabad", totalCases: 3450, urgentCases: 540, counsellors: 15, resolutionRate: 87, trend: "down" },
    ],
  },
  mh: {
    id: "mh",
    code: "MH",
    name: "Maharashtra",
    capital: "Mumbai",
    region: "West",
    riskLevel: "High",
    nodalOfficer: "Smt. Rohini Patil (WCD Directorate)",
    nodalPhone: "022-22027050 / 181",
    helpline181Active: true,
    activeFlyingSquads: 16,
    center: { x: 180, y: 435 },
    bounds: { minX: 93, maxX: 266, minY: 364, maxY: 506, width: 173, height: 142 },
    periods: {
      live: { totalCases: 215, urgentCases: 36, saathiCases: 34, helplineCalls: 345, resolutionRate: 88, avgResponseMins: 12 },
      week: { totalCases: 1420, urgentCases: 210, saathiCases: 198, helplineCalls: 2240, resolutionRate: 89, avgResponseMins: 15 },
      month: { totalCases: 5890, urgentCases: 860, saathiCases: 780, helplineCalls: 8900, resolutionRate: 91, avgResponseMins: 19 },
      annual: { totalCases: 39540, urgentCases: 5820, saathiCases: 3850, helplineCalls: 54200, resolutionRate: 92, avgResponseMins: 20 },
    },
    districts: [
      { name: "Mumbai Suburban", totalCases: 7820, urgentCases: 1180, counsellors: 38, resolutionRate: 94, trend: "down" },
      { name: "Pune", totalCases: 6410, urgentCases: 920, counsellors: 30, resolutionRate: 92, trend: "stable" },
      { name: "Nagpur", totalCases: 4120, urgentCases: 610, counsellors: 22, resolutionRate: 90, trend: "down" },
      { name: "Thane", totalCases: 3950, urgentCases: 580, counsellors: 20, resolutionRate: 89, trend: "up" },
      { name: "Nashik", totalCases: 2840, urgentCases: 410, counsellors: 14, resolutionRate: 88, trend: "stable" },
      { name: "Chhatrapati Sambhajinagar", totalCases: 2410, urgentCases: 360, counsellors: 12, resolutionRate: 87, trend: "down" },
    ],
  },
  rj: {
    id: "rj",
    code: "RJ",
    name: "Rajasthan",
    capital: "Jaipur",
    region: "North",
    riskLevel: "Critical",
    nodalOfficer: "Shri Mahaveer Prasad, RACS (Dir. Social Justice)",
    nodalPhone: "0141-2227181 / 181",
    helpline181Active: true,
    activeFlyingSquads: 14,
    center: { x: 119, y: 257 },
    bounds: { minX: 27, maxX: 211, minY: 173, maxY: 341, width: 184, height: 168 },
    periods: {
      live: { totalCases: 188, urgentCases: 32, saathiCases: 26, helplineCalls: 280, resolutionRate: 80, avgResponseMins: 16 },
      week: { totalCases: 1240, urgentCases: 195, saathiCases: 164, helplineCalls: 1890, resolutionRate: 83, avgResponseMins: 21 },
      month: { totalCases: 4920, urgentCases: 740, saathiCases: 610, helplineCalls: 7450, resolutionRate: 86, avgResponseMins: 24 },
      annual: { totalCases: 31540, urgentCases: 5120, saathiCases: 2980, helplineCalls: 44500, resolutionRate: 88, avgResponseMins: 26 },
    },
    districts: [
      { name: "Jaipur", totalCases: 6140, urgentCases: 980, counsellors: 28, resolutionRate: 91, trend: "down" },
      { name: "Jodhpur", totalCases: 3890, urgentCases: 620, counsellors: 18, resolutionRate: 87, trend: "stable" },
      { name: "Alwar", totalCases: 3420, urgentCases: 590, counsellors: 16, resolutionRate: 84, trend: "up" },
      { name: "Kota", totalCases: 2910, urgentCases: 480, counsellors: 15, resolutionRate: 89, trend: "down" },
      { name: "Udaipur", totalCases: 2650, urgentCases: 410, counsellors: 14, resolutionRate: 88, trend: "stable" },
    ],
  },
  dl: {
    id: "dl",
    code: "DL",
    name: "Delhi NCR",
    capital: "New Delhi",
    region: "North",
    riskLevel: "Critical",
    nodalOfficer: "Smt. Rashmi Sharma, DANICS (DCW Liaison)",
    nodalPhone: "011-23379181 / 181",
    helpline181Active: true,
    activeFlyingSquads: 15,
    center: { x: 186, y: 210 },
    bounds: { minX: 181, maxX: 192, minY: 205, maxY: 216, width: 11, height: 11 },
    periods: {
      live: { totalCases: 120, urgentCases: 26, saathiCases: 22, helplineCalls: 310, resolutionRate: 92, avgResponseMins: 9 },
      week: { totalCases: 780, urgentCases: 145, saathiCases: 120, helplineCalls: 1980, resolutionRate: 93, avgResponseMins: 11 },
      month: { totalCases: 3100, urgentCases: 540, saathiCases: 430, helplineCalls: 7800, resolutionRate: 94, avgResponseMins: 13 },
      annual: { totalCases: 14250, urgentCases: 2840, saathiCases: 1810, helplineCalls: 32400, resolutionRate: 95, avgResponseMins: 14 },
    },
    districts: [
      { name: "South Delhi", totalCases: 2890, urgentCases: 540, counsellors: 18, resolutionRate: 96, trend: "down" },
      { name: "North West Delhi", totalCases: 2640, urgentCases: 510, counsellors: 16, resolutionRate: 93, trend: "stable" },
      { name: "West Delhi", totalCases: 2120, urgentCases: 420, counsellors: 14, resolutionRate: 94, trend: "down" },
      { name: "South East Delhi", totalCases: 1980, urgentCases: 390, counsellors: 13, resolutionRate: 92, trend: "up" },
      { name: "Central Delhi", totalCases: 1740, urgentCases: 320, counsellors: 12, resolutionRate: 97, trend: "down" },
    ],
  },
  wb: {
    id: "wb",
    code: "WB",
    name: "West Bengal",
    capital: "Kolkata",
    region: "East",
    riskLevel: "High",
    nodalOfficer: "Dr. Ananya Ray (Social Welfare Commission)",
    nodalPhone: "033-23371810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 13,
    center: { x: 412, y: 310 },
    bounds: { minX: 369, maxX: 454, minY: 244, maxY: 375, width: 85, height: 131 },
    periods: {
      live: { totalCases: 145, urgentCases: 24, saathiCases: 20, helplineCalls: 240, resolutionRate: 84, avgResponseMins: 17 },
      week: { totalCases: 980, urgentCases: 155, saathiCases: 130, helplineCalls: 1620, resolutionRate: 86, avgResponseMins: 20 },
      month: { totalCases: 4120, urgentCases: 620, saathiCases: 480, helplineCalls: 6540, resolutionRate: 88, avgResponseMins: 23 },
      annual: { totalCases: 26410, urgentCases: 3950, saathiCases: 2490, helplineCalls: 39400, resolutionRate: 89, avgResponseMins: 24 },
    },
    districts: [
      { name: "Kolkata", totalCases: 5120, urgentCases: 760, counsellors: 24, resolutionRate: 92, trend: "down" },
      { name: "North 24 Parganas", totalCases: 4650, urgentCases: 690, counsellors: 20, resolutionRate: 88, trend: "stable" },
      { name: "South 24 Parganas", totalCases: 3890, urgentCases: 580, counsellors: 17, resolutionRate: 86, trend: "up" },
      { name: "Howrah", totalCases: 2980, urgentCases: 440, counsellors: 14, resolutionRate: 89, trend: "down" },
      { name: "Murshidabad", totalCases: 2410, urgentCases: 370, counsellors: 12, resolutionRate: 85, trend: "stable" },
    ],
  },
  mp: {
    id: "mp",
    code: "MP",
    name: "Madhya Pradesh",
    capital: "Bhopal",
    region: "Central",
    riskLevel: "High",
    nodalOfficer: "Smt. Vandana Tiwari (Mahila Vitt Vikas Nigam)",
    nodalPhone: "0755-2551810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 12,
    center: { x: 214, y: 319 },
    bounds: { minX: 122, maxX: 306, minY: 252, maxY: 386, width: 184, height: 133 },
    periods: {
      live: { totalCases: 135, urgentCases: 21, saathiCases: 18, helplineCalls: 210, resolutionRate: 82, avgResponseMins: 19 },
      week: { totalCases: 890, urgentCases: 135, saathiCases: 115, helplineCalls: 1450, resolutionRate: 84, avgResponseMins: 22 },
      month: { totalCases: 3650, urgentCases: 540, saathiCases: 420, helplineCalls: 5900, resolutionRate: 87, avgResponseMins: 25 },
      annual: { totalCases: 22850, urgentCases: 3410, saathiCases: 2160, helplineCalls: 34200, resolutionRate: 88, avgResponseMins: 26 },
    },
    districts: [
      { name: "Indore", totalCases: 4890, urgentCases: 710, counsellors: 22, resolutionRate: 91, trend: "down" },
      { name: "Bhopal", totalCases: 4250, urgentCases: 630, counsellors: 20, resolutionRate: 90, trend: "down" },
      { name: "Jabalpur", totalCases: 3120, urgentCases: 460, counsellors: 15, resolutionRate: 87, trend: "stable" },
      { name: "Gwalior", totalCases: 2840, urgentCases: 420, counsellors: 14, resolutionRate: 86, trend: "up" },
      { name: "Ujjain", totalCases: 2110, urgentCases: 310, counsellors: 11, resolutionRate: 88, trend: "stable" },
    ],
  },
  tg: {
    id: "tg",
    code: "TG",
    name: "Telangana",
    capital: "Hyderabad",
    region: "South",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Swati Lakra, IPS (Women Safety Wing)",
    nodalPhone: "040-27852181 / 181",
    helpline181Active: true,
    activeFlyingSquads: 11,
    center: { x: 237, y: 457 },
    bounds: { minX: 189, maxX: 285, minY: 412, maxY: 502, width: 95, height: 90 },
    periods: {
      live: { totalCases: 95, urgentCases: 14, saathiCases: 15, helplineCalls: 175, resolutionRate: 91, avgResponseMins: 13 },
      week: { totalCases: 620, urgentCases: 88, saathiCases: 82, helplineCalls: 1180, resolutionRate: 92, avgResponseMins: 16 },
      month: { totalCases: 2540, urgentCases: 340, saathiCases: 310, helplineCalls: 4800, resolutionRate: 94, avgResponseMins: 18 },
      annual: { totalCases: 15900, urgentCases: 2150, saathiCases: 1590, helplineCalls: 23800, resolutionRate: 94, avgResponseMins: 19 },
    },
    districts: [
      { name: "Hyderabad", totalCases: 4890, urgentCases: 640, counsellors: 25, resolutionRate: 96, trend: "down" },
      { name: "Medchal-Malkajgiri", totalCases: 2950, urgentCases: 390, counsellors: 16, resolutionRate: 94, trend: "stable" },
      { name: "Rangareddy", totalCases: 2640, urgentCases: 360, counsellors: 14, resolutionRate: 93, trend: "down" },
      { name: "Warangal", totalCases: 1840, urgentCases: 240, counsellors: 10, resolutionRate: 92, trend: "up" },
      { name: "Karimnagar", totalCases: 1420, urgentCases: 180, counsellors: 9, resolutionRate: 93, trend: "stable" },
    ],
  },
  ap: {
    id: "ap",
    code: "AP",
    name: "Andhra Pradesh",
    capital: "Amaravati",
    region: "South",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. D. Deepika, IPS (Disha Cell)",
    nodalPhone: "0863-2341810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 10,
    center: { x: 263, y: 500 },
    bounds: { minX: 179, maxX: 347, minY: 428, maxY: 571, width: 167, height: 143 },
    periods: {
      live: { totalCases: 105, urgentCases: 16, saathiCases: 15, helplineCalls: 190, resolutionRate: 89, avgResponseMins: 15 },
      week: { totalCases: 690, urgentCases: 95, saathiCases: 86, helplineCalls: 1320, resolutionRate: 90, avgResponseMins: 18 },
      month: { totalCases: 2840, urgentCases: 380, saathiCases: 330, helplineCalls: 5400, resolutionRate: 92, avgResponseMins: 20 },
      annual: { totalCases: 17600, urgentCases: 2410, saathiCases: 1620, helplineCalls: 26500, resolutionRate: 93, avgResponseMins: 21 },
    },
    districts: [
      { name: "Visakhapatnam", totalCases: 3950, urgentCases: 520, counsellors: 20, resolutionRate: 95, trend: "down" },
      { name: "Vijayawada (NTR)", totalCases: 3120, urgentCases: 430, counsellors: 16, resolutionRate: 93, trend: "down" },
      { name: "Guntur", totalCases: 2640, urgentCases: 370, counsellors: 14, resolutionRate: 91, trend: "stable" },
      { name: "Kurnool", totalCases: 2140, urgentCases: 290, counsellors: 12, resolutionRate: 90, trend: "up" },
      { name: "Tirupati", totalCases: 1890, urgentCases: 250, counsellors: 11, resolutionRate: 92, trend: "stable" },
    ],
  },
  ka: {
    id: "ka",
    code: "KA",
    name: "Karnataka",
    capital: "Bengaluru",
    region: "South",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. K. Ratnaprabha (Parihar / Vanitha Sahayavani)",
    nodalPhone: "080-22941810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 12,
    center: { x: 171, y: 519 },
    bounds: { minX: 124, maxX: 218, minY: 444, maxY: 593, width: 94, height: 149 },
    periods: {
      live: { totalCases: 85, urgentCases: 12, saathiCases: 14, helplineCalls: 160, resolutionRate: 92, avgResponseMins: 11 },
      week: { totalCases: 540, urgentCases: 74, saathiCases: 72, helplineCalls: 1040, resolutionRate: 93, avgResponseMins: 14 },
      month: { totalCases: 2150, urgentCases: 290, saathiCases: 270, helplineCalls: 4200, resolutionRate: 95, avgResponseMins: 17 },
      annual: { totalCases: 13200, urgentCases: 1890, saathiCases: 1670, helplineCalls: 21800, resolutionRate: 95, avgResponseMins: 18 },
    },
    districts: [
      { name: "Bengaluru Urban", totalCases: 5140, urgentCases: 740, counsellors: 26, resolutionRate: 97, trend: "down" },
      { name: "Mysuru", totalCases: 1890, urgentCases: 260, counsellors: 12, resolutionRate: 94, trend: "stable" },
      { name: "Belagavi", totalCases: 1640, urgentCases: 230, counsellors: 11, resolutionRate: 92, trend: "up" },
      { name: "Hubballi-Dharwad", totalCases: 1390, urgentCases: 190, counsellors: 10, resolutionRate: 93, trend: "down" },
      { name: "Mangaluru (Dakshina Kannada)", totalCases: 1120, urgentCases: 150, counsellors: 9, resolutionRate: 96, trend: "stable" },
    ],
  },
  tn: {
    id: "tn",
    code: "TN",
    name: "Tamil Nadu",
    capital: "Chennai",
    region: "South",
    riskLevel: "Moderate",
    nodalOfficer: "Dr. K. Manivasan, IAS (Social Welfare & Women Empowerment)",
    nodalPhone: "044-25611810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 11,
    center: { x: 211, y: 609 },
    bounds: { minX: 168, maxX: 255, minY: 551, maxY: 668, width: 86, height: 117 },
    periods: {
      live: { totalCases: 72, urgentCases: 9, saathiCases: 11, helplineCalls: 140, resolutionRate: 94, avgResponseMins: 12 },
      week: { totalCases: 460, urgentCases: 58, saathiCases: 62, helplineCalls: 910, resolutionRate: 95, avgResponseMins: 15 },
      month: { totalCases: 1820, urgentCases: 220, saathiCases: 230, helplineCalls: 3650, resolutionRate: 96, avgResponseMins: 17 },
      annual: { totalCases: 10800, urgentCases: 1380, saathiCases: 1530, helplineCalls: 19100, resolutionRate: 97, avgResponseMins: 18 },
    },
    districts: [
      { name: "Chennai", totalCases: 3840, urgentCases: 490, counsellors: 22, resolutionRate: 98, trend: "down" },
      { name: "Coimbatore", totalCases: 1920, urgentCases: 240, counsellors: 13, resolutionRate: 96, trend: "stable" },
      { name: "Madurai", totalCases: 1650, urgentCases: 210, counsellors: 11, resolutionRate: 95, trend: "down" },
      { name: "Tiruchirappalli", totalCases: 1240, urgentCases: 150, counsellors: 9, resolutionRate: 96, trend: "stable" },
      { name: "Salem", totalCases: 1050, urgentCases: 130, counsellors: 8, resolutionRate: 94, trend: "up" },
    ],
  },
  br: {
    id: "br",
    code: "BR",
    name: "Bihar",
    capital: "Patna",
    region: "East",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Bandana Preyashi, IAS (Women Development Corp.)",
    nodalPhone: "0612-2501810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 11,
    center: { x: 369, y: 275 },
    bounds: { minX: 317, maxX: 421, minY: 237, maxY: 313, width: 104, height: 75 },
    periods: {
      live: { totalCases: 98, urgentCases: 15, saathiCases: 12, helplineCalls: 165, resolutionRate: 81, avgResponseMins: 18 },
      week: { totalCases: 620, urgentCases: 95, saathiCases: 76, helplineCalls: 1080, resolutionRate: 83, avgResponseMins: 22 },
      month: { totalCases: 2480, urgentCases: 370, saathiCases: 280, helplineCalls: 4350, resolutionRate: 86, avgResponseMins: 25 },
      annual: { totalCases: 14800, urgentCases: 2310, saathiCases: 1480, helplineCalls: 22900, resolutionRate: 87, avgResponseMins: 27 },
    },
    districts: [
      { name: "Patna", totalCases: 4120, urgentCases: 620, counsellors: 20, resolutionRate: 90, trend: "down" },
      { name: "Muzaffarpur", totalCases: 2180, urgentCases: 340, counsellors: 13, resolutionRate: 86, trend: "stable" },
      { name: "Gaya", totalCases: 1940, urgentCases: 310, counsellors: 12, resolutionRate: 85, trend: "up" },
      { name: "Bhagalpur", totalCases: 1620, urgentCases: 250, counsellors: 10, resolutionRate: 87, trend: "down" },
      { name: "Darbhanga", totalCases: 1390, urgentCases: 210, counsellors: 9, resolutionRate: 86, trend: "stable" },
    ],
  },
  gj: {
    id: "gj",
    code: "GJ",
    name: "Gujarat",
    capital: "Gandhinagar",
    region: "West",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Manisha Chandra, IAS (Women & Child Welfare)",
    nodalPhone: "079-23251810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 10,
    center: { x: 66, y: 355 },
    bounds: { minX: 0, maxX: 132, minY: 303, maxY: 407, width: 132, height: 104 },
    periods: {
      live: { totalCases: 76, urgentCases: 10, saathiCases: 12, helplineCalls: 130, resolutionRate: 91, avgResponseMins: 13 },
      week: { totalCases: 480, urgentCases: 64, saathiCases: 68, helplineCalls: 860, resolutionRate: 92, avgResponseMins: 16 },
      month: { totalCases: 1940, urgentCases: 240, saathiCases: 250, helplineCalls: 3450, resolutionRate: 94, avgResponseMins: 18 },
      annual: { totalCases: 11500, urgentCases: 1520, saathiCases: 1510, helplineCalls: 18700, resolutionRate: 95, avgResponseMins: 19 },
    },
    districts: [
      { name: "Ahmedabad", totalCases: 4120, urgentCases: 540, counsellors: 22, resolutionRate: 96, trend: "down" },
      { name: "Surat", totalCases: 3240, urgentCases: 420, counsellors: 18, resolutionRate: 94, trend: "stable" },
      { name: "Vadodara", totalCases: 1890, urgentCases: 240, counsellors: 12, resolutionRate: 95, trend: "down" },
      { name: "Rajkot", totalCases: 1450, urgentCases: 180, counsellors: 10, resolutionRate: 93, trend: "up" },
      { name: "Bhavnagar", totalCases: 890, urgentCases: 110, counsellors: 7, resolutionRate: 94, trend: "stable" },
    ],
  },
  pb: {
    id: "pb",
    code: "PB",
    name: "Punjab",
    capital: "Chandigarh",
    region: "North",
    riskLevel: "Moderate",
    nodalOfficer: "Dr. Amrit Kaur, IPS (Community Policing & Women Wing)",
    nodalPhone: "0172-2741810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 8,
    center: { x: 151, y: 152 },
    bounds: { minX: 119, maxX: 183, minY: 115, maxY: 189, width: 64, height: 74 },
    periods: {
      live: { totalCases: 54, urgentCases: 7, saathiCases: 8, helplineCalls: 95, resolutionRate: 87, avgResponseMins: 15 },
      week: { totalCases: 340, urgentCases: 42, saathiCases: 45, helplineCalls: 620, resolutionRate: 88, avgResponseMins: 18 },
      month: { totalCases: 1380, urgentCases: 165, saathiCases: 160, helplineCalls: 2450, resolutionRate: 90, avgResponseMins: 20 },
      annual: { totalCases: 8100, urgentCases: 980, saathiCases: 920, helplineCalls: 14100, resolutionRate: 91, avgResponseMins: 21 },
    },
    districts: [
      { name: "Ludhiana", totalCases: 2640, urgentCases: 320, counsellors: 14, resolutionRate: 92, trend: "down" },
      { name: "Amritsar", totalCases: 1980, urgentCases: 240, counsellors: 12, resolutionRate: 90, trend: "stable" },
      { name: "Jalandhar", totalCases: 1620, urgentCases: 190, counsellors: 10, resolutionRate: 91, trend: "down" },
      { name: "Patiala", totalCases: 1120, urgentCases: 130, counsellors: 8, resolutionRate: 89, trend: "up" },
    ],
  },
  hr: {
    id: "hr",
    code: "HR",
    name: "Haryana",
    capital: "Chandigarh",
    region: "North",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Mamta Singh, IPS (Crime Against Women)",
    nodalPhone: "0172-2581810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 8,
    center: { x: 164, y: 195 },
    bounds: { minX: 131, maxX: 197, minY: 155, maxY: 234, width: 65, height: 79 },
    periods: {
      live: { totalCases: 52, urgentCases: 8, saathiCases: 8, helplineCalls: 90, resolutionRate: 86, avgResponseMins: 14 },
      week: { totalCases: 330, urgentCases: 48, saathiCases: 44, helplineCalls: 590, resolutionRate: 87, avgResponseMins: 17 },
      month: { totalCases: 1320, urgentCases: 185, saathiCases: 155, helplineCalls: 2380, resolutionRate: 89, avgResponseMins: 19 },
      annual: { totalCases: 7900, urgentCases: 1120, saathiCases: 940, helplineCalls: 13900, resolutionRate: 90, avgResponseMins: 20 },
    },
    districts: [
      { name: "Gurugram", totalCases: 2950, urgentCases: 410, counsellors: 16, resolutionRate: 93, trend: "down" },
      { name: "Faridabad", totalCases: 2140, urgentCases: 290, counsellors: 13, resolutionRate: 90, trend: "stable" },
      { name: "Hisar", totalCases: 1240, urgentCases: 170, counsellors: 8, resolutionRate: 88, trend: "up" },
      { name: "Karnal", totalCases: 980, urgentCases: 130, counsellors: 7, resolutionRate: 89, trend: "down" },
    ],
  },
  or: {
    id: "or",
    code: "OR",
    name: "Odisha",
    capital: "Bhubaneswar",
    region: "East",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Shubha Sarma, IAS (WCD Department)",
    nodalPhone: "0674-2391810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 9,
    center: { x: 340, y: 405 },
    bounds: { minX: 276, maxX: 404, minY: 352, maxY: 458, width: 128, height: 106 },
    periods: {
      live: { totalCases: 64, urgentCases: 8, saathiCases: 9, helplineCalls: 110, resolutionRate: 89, avgResponseMins: 16 },
      week: { totalCases: 410, urgentCases: 52, saathiCases: 54, helplineCalls: 720, resolutionRate: 90, avgResponseMins: 19 },
      month: { totalCases: 1640, urgentCases: 210, saathiCases: 210, helplineCalls: 2890, resolutionRate: 92, avgResponseMins: 21 },
      annual: { totalCases: 9600, urgentCases: 1240, saathiCases: 1190, helplineCalls: 17200, resolutionRate: 93, avgResponseMins: 22 },
    },
    districts: [
      { name: "Khordha (Bhubaneswar)", totalCases: 3450, urgentCases: 440, counsellors: 16, resolutionRate: 95, trend: "down" },
      { name: "Cuttack", totalCases: 2180, urgentCases: 280, counsellors: 12, resolutionRate: 93, trend: "stable" },
      { name: "Ganjam", totalCases: 1740, urgentCases: 220, counsellors: 10, resolutionRate: 91, trend: "down" },
      { name: "Sundargarh", totalCases: 1240, urgentCases: 160, counsellors: 8, resolutionRate: 90, trend: "up" },
    ],
  },
  kl: {
    id: "kl",
    code: "KL",
    name: "Kerala",
    capital: "Thiruvananthapuram",
    region: "South",
    riskLevel: "Low",
    nodalOfficer: "Smt. B. Sandhya, IPS (Kanal & Mitra 181)",
    nodalPhone: "0471-2321810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 7,
    center: { x: 166, y: 615 },
    bounds: { minX: 140, maxX: 193, minY: 567, maxY: 663, width: 53, height: 96 },
    periods: {
      live: { totalCases: 42, urgentCases: 5, saathiCases: 7, helplineCalls: 85, resolutionRate: 96, avgResponseMins: 10 },
      week: { totalCases: 270, urgentCases: 31, saathiCases: 38, helplineCalls: 540, resolutionRate: 97, avgResponseMins: 12 },
      month: { totalCases: 1080, urgentCases: 120, saathiCases: 145, helplineCalls: 2150, resolutionRate: 98, avgResponseMins: 14 },
      annual: { totalCases: 6400, urgentCases: 720, saathiCases: 810, helplineCalls: 13200, resolutionRate: 98, avgResponseMins: 15 },
    },
    districts: [
      { name: "Thiruvananthapuram", totalCases: 1980, urgentCases: 220, counsellors: 14, resolutionRate: 99, trend: "down" },
      { name: "Ernakulam (Kochi)", totalCases: 1840, urgentCases: 210, counsellors: 13, resolutionRate: 98, trend: "down" },
      { name: "Kozhikode", totalCases: 1320, urgentCases: 150, counsellors: 10, resolutionRate: 97, trend: "stable" },
      { name: "Thrissur", totalCases: 980, urgentCases: 110, counsellors: 8, resolutionRate: 98, trend: "stable" },
    ],
  },
  jh: {
    id: "jh",
    code: "JH",
    name: "Jharkhand",
    capital: "Ranchi",
    region: "East",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Kripa Nand Jha, IAS (Social Welfare)",
    nodalPhone: "0651-2401810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 7,
    center: { x: 366, y: 327 },
    bounds: { minX: 317, maxX: 414, minY: 288, maxY: 365, width: 97, height: 77 },
    periods: {
      live: { totalCases: 41, urgentCases: 6, saathiCases: 6, helplineCalls: 70, resolutionRate: 85, avgResponseMins: 17 },
      week: { totalCases: 260, urgentCases: 38, saathiCases: 35, helplineCalls: 450, resolutionRate: 86, avgResponseMins: 20 },
      month: { totalCases: 1040, urgentCases: 150, saathiCases: 130, helplineCalls: 1820, resolutionRate: 88, avgResponseMins: 23 },
      annual: { totalCases: 6100, urgentCases: 890, saathiCases: 770, helplineCalls: 11500, resolutionRate: 89, avgResponseMins: 24 },
    },
    districts: [
      { name: "Ranchi", totalCases: 2450, urgentCases: 360, counsellors: 14, resolutionRate: 91, trend: "down" },
      { name: "East Singhbhum (Jamshedpur)", totalCases: 1680, urgentCases: 240, counsellors: 11, resolutionRate: 89, trend: "stable" },
      { name: "Dhanbad", totalCases: 1240, urgentCases: 180, counsellors: 9, resolutionRate: 87, trend: "up" },
    ],
  },
  ct: {
    id: "ct",
    code: "CG",
    name: "Chhattisgarh",
    capital: "Raipur",
    region: "Central",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Reena Baba Saheb Kangale, IAS (WCD)",
    nodalPhone: "0771-2221810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 7,
    center: { x: 296, y: 388 },
    bounds: { minX: 252, maxX: 339, minY: 317, maxY: 459, width: 87, height: 142 },
    periods: {
      live: { totalCases: 38, urgentCases: 5, saathiCases: 5, helplineCalls: 65, resolutionRate: 86, avgResponseMins: 17 },
      week: { totalCases: 245, urgentCases: 34, saathiCases: 32, helplineCalls: 420, resolutionRate: 87, avgResponseMins: 21 },
      month: { totalCases: 980, urgentCases: 135, saathiCases: 120, helplineCalls: 1690, resolutionRate: 89, avgResponseMins: 24 },
      annual: { totalCases: 5800, urgentCases: 810, saathiCases: 650, helplineCalls: 10200, resolutionRate: 90, avgResponseMins: 25 },
    },
    districts: [
      { name: "Raipur", totalCases: 2310, urgentCases: 320, counsellors: 13, resolutionRate: 92, trend: "down" },
      { name: "Durg-Bhilai", totalCases: 1740, urgentCases: 240, counsellors: 11, resolutionRate: 90, trend: "stable" },
      { name: "Bilaspur", totalCases: 1120, urgentCases: 150, counsellors: 8, resolutionRate: 88, trend: "up" },
    ],
  },
  as: {
    id: "as",
    code: "AS",
    name: "Assam",
    capital: "Dispur",
    region: "North-East",
    riskLevel: "High",
    nodalOfficer: "Dr. Lakshmanan S., IAS (Social Welfare)",
    nodalPhone: "0361-2231810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 8,
    center: { x: 516, y: 271 },
    bounds: { minX: 450, maxX: 583, minY: 226, maxY: 316, width: 132, height: 90 },
    periods: {
      live: { totalCases: 78, urgentCases: 12, saathiCases: 10, helplineCalls: 120, resolutionRate: 83, avgResponseMins: 18 },
      week: { totalCases: 490, urgentCases: 76, saathiCases: 64, helplineCalls: 780, resolutionRate: 85, avgResponseMins: 22 },
      month: { totalCases: 1980, urgentCases: 310, saathiCases: 240, helplineCalls: 3120, resolutionRate: 87, avgResponseMins: 24 },
      annual: { totalCases: 12420, urgentCases: 1980, saathiCases: 1340, helplineCalls: 19400, resolutionRate: 88, avgResponseMins: 26 },
    },
    districts: [
      { name: "Kamrup Metropolitan (Guwahati)", totalCases: 4120, urgentCases: 640, counsellors: 18, resolutionRate: 91, trend: "down" },
      { name: "Dibrugarh", totalCases: 2450, urgentCases: 390, counsellors: 12, resolutionRate: 88, trend: "stable" },
      { name: "Silchar (Cachar)", totalCases: 1980, urgentCases: 310, counsellors: 10, resolutionRate: 86, trend: "up" },
      { name: "Nagaon", totalCases: 1650, urgentCases: 260, counsellors: 9, resolutionRate: 85, trend: "stable" },
    ],
  },
  jk: {
    id: "jk",
    code: "JK",
    name: "Jammu and Kashmir & Ladakh",
    capital: "Srinagar / Jammu",
    region: "North",
    riskLevel: "Low",
    nodalOfficer: "Smt. Sheetal Nanda, IAS (Social Welfare)",
    nodalPhone: "0194-2451810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 6,
    center: { x: 173, y: 61 },
    bounds: { minX: 93, maxX: 253, minY: 0, maxY: 122, width: 160, height: 122 },
    periods: {
      live: { totalCases: 28, urgentCases: 4, saathiCases: 3, helplineCalls: 50, resolutionRate: 89, avgResponseMins: 16 },
      week: { totalCases: 180, urgentCases: 26, saathiCases: 22, helplineCalls: 320, resolutionRate: 90, avgResponseMins: 19 },
      month: { totalCases: 720, urgentCases: 102, saathiCases: 84, helplineCalls: 1280, resolutionRate: 92, avgResponseMins: 22 },
      annual: { totalCases: 4300, urgentCases: 610, saathiCases: 490, helplineCalls: 8100, resolutionRate: 93, avgResponseMins: 23 },
    },
    districts: [
      { name: "Srinagar", totalCases: 1750, urgentCases: 250, counsellors: 11, resolutionRate: 94, trend: "down" },
      { name: "Jammu", totalCases: 1620, urgentCases: 230, counsellors: 10, resolutionRate: 93, trend: "down" },
      { name: "Leh Ladakh", totalCases: 480, urgentCases: 60, counsellors: 5, resolutionRate: 95, trend: "stable" },
    ],
  },
  ut: {
    id: "ut",
    code: "UK",
    name: "Uttarakhand",
    capital: "Dehradun",
    region: "North",
    riskLevel: "Low",
    nodalOfficer: "Smt. Saujanya, IAS (Women Empowerment)",
    nodalPhone: "0135-2711810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 5,
    center: { x: 232, y: 175 },
    bounds: { minX: 196, maxX: 269, minY: 142, maxY: 209, width: 72, height: 67 },
    periods: {
      live: { totalCases: 16, urgentCases: 2, saathiCases: 2, helplineCalls: 30, resolutionRate: 91, avgResponseMins: 14 },
      week: { totalCases: 105, urgentCases: 14, saathiCases: 15, helplineCalls: 190, resolutionRate: 92, avgResponseMins: 17 },
      month: { totalCases: 420, urgentCases: 54, saathiCases: 55, helplineCalls: 750, resolutionRate: 94, avgResponseMins: 19 },
      annual: { totalCases: 2400, urgentCases: 310, saathiCases: 340, helplineCalls: 4800, resolutionRate: 94, avgResponseMins: 20 },
    },
    districts: [
      { name: "Dehradun", totalCases: 1180, urgentCases: 150, counsellors: 9, resolutionRate: 96, trend: "down" },
      { name: "Haridwar", totalCases: 740, urgentCases: 95, counsellors: 7, resolutionRate: 93, trend: "stable" },
      { name: "Nainital", totalCases: 420, urgentCases: 55, counsellors: 5, resolutionRate: 94, trend: "down" },
    ],
  },
  hp: {
    id: "hp",
    code: "HP",
    name: "Himachal Pradesh",
    capital: "Shimla",
    region: "North",
    riskLevel: "Low",
    nodalOfficer: "Smt. M. Sudha Devi, IAS (WCD)",
    nodalPhone: "0177-2621810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 4,
    center: { x: 191, y: 133 },
    bounds: { minX: 155, maxX: 226, minY: 98, maxY: 168, width: 72, height: 71 },
    periods: {
      live: { totalCases: 12, urgentCases: 1, saathiCases: 2, helplineCalls: 25, resolutionRate: 94, avgResponseMins: 14 },
      week: { totalCases: 80, urgentCases: 9, saathiCases: 12, helplineCalls: 160, resolutionRate: 95, avgResponseMins: 16 },
      month: { totalCases: 320, urgentCases: 36, saathiCases: 48, helplineCalls: 640, resolutionRate: 96, avgResponseMins: 18 },
      annual: { totalCases: 1950, urgentCases: 220, saathiCases: 310, helplineCalls: 4100, resolutionRate: 96, avgResponseMins: 19 },
    },
    districts: [
      { name: "Kangra", totalCases: 740, urgentCases: 85, counsellors: 6, resolutionRate: 97, trend: "down" },
      { name: "Shimla", totalCases: 680, urgentCases: 75, counsellors: 6, resolutionRate: 96, trend: "down" },
      { name: "Mandi", totalCases: 410, urgentCases: 45, counsellors: 4, resolutionRate: 95, trend: "stable" },
    ],
  },
  ga: {
    id: "ga",
    code: "GA",
    name: "Goa",
    capital: "Panaji",
    region: "West",
    riskLevel: "Low",
    nodalOfficer: "Smt. Deepali Naik (Directorate of WCD)",
    nodalPhone: "0832-2221810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 3,
    center: { x: 122, y: 512 },
    bounds: { minX: 115, maxX: 129, minY: 502, maxY: 522, width: 14, height: 20 },
    periods: {
      live: { totalCases: 4, urgentCases: 1, saathiCases: 1, helplineCalls: 12, resolutionRate: 96, avgResponseMins: 10 },
      week: { totalCases: 28, urgentCases: 3, saathiCases: 5, helplineCalls: 75, resolutionRate: 97, avgResponseMins: 12 },
      month: { totalCases: 110, urgentCases: 12, saathiCases: 20, helplineCalls: 310, resolutionRate: 98, avgResponseMins: 14 },
      annual: { totalCases: 620, urgentCases: 70, saathiCases: 135, helplineCalls: 1850, resolutionRate: 98, avgResponseMins: 15 },
    },
    districts: [
      { name: "North Goa", totalCases: 360, urgentCases: 40, counsellors: 5, resolutionRate: 98, trend: "down" },
      { name: "South Goa", totalCases: 260, urgentCases: 30, counsellors: 4, resolutionRate: 98, trend: "stable" },
    ],
  },
  tr: {
    id: "tr",
    code: "TR",
    name: "Tripura",
    capital: "Agartala",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Shri B.S. Mishra, IAS (Social Welfare)",
    nodalPhone: "0381-2321810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 3,
    center: { x: 493, y: 325 },
    bounds: { minX: 481, maxX: 506, minY: 307, maxY: 343, width: 25, height: 36 },
    periods: {
      live: { totalCases: 6, urgentCases: 1, saathiCases: 1, helplineCalls: 15, resolutionRate: 91, avgResponseMins: 15 },
      week: { totalCases: 40, urgentCases: 5, saathiCases: 6, helplineCalls: 95, resolutionRate: 92, avgResponseMins: 18 },
      month: { totalCases: 160, urgentCases: 22, saathiCases: 24, helplineCalls: 390, resolutionRate: 94, avgResponseMins: 20 },
      annual: { totalCases: 950, urgentCases: 130, saathiCases: 140, helplineCalls: 2450, resolutionRate: 94, avgResponseMins: 21 },
    },
    districts: [
      { name: "West Tripura (Agartala)", totalCases: 560, urgentCases: 75, counsellors: 5, resolutionRate: 95, trend: "down" },
      { name: "Gomati", totalCases: 210, urgentCases: 30, counsellors: 3, resolutionRate: 93, trend: "stable" },
    ],
  },
  ml: {
    id: "ml",
    code: "ML",
    name: "Meghalaya",
    capital: "Shillong",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Smt. I. Mawlong, MCS (Social Welfare)",
    nodalPhone: "0364-2221810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 3,
    center: { x: 484, y: 283 },
    bounds: { minX: 453, maxX: 515, minY: 270, maxY: 295, width: 62, height: 25 },
    periods: {
      live: { totalCases: 5, urgentCases: 1, saathiCases: 1, helplineCalls: 12, resolutionRate: 92, avgResponseMins: 15 },
      week: { totalCases: 35, urgentCases: 4, saathiCases: 5, helplineCalls: 85, resolutionRate: 93, avgResponseMins: 18 },
      month: { totalCases: 140, urgentCases: 18, saathiCases: 22, helplineCalls: 340, resolutionRate: 95, avgResponseMins: 20 },
      annual: { totalCases: 840, urgentCases: 110, saathiCases: 130, helplineCalls: 2150, resolutionRate: 95, avgResponseMins: 21 },
    },
    districts: [
      { name: "East Khasi Hills (Shillong)", totalCases: 510, urgentCases: 65, counsellors: 5, resolutionRate: 96, trend: "down" },
      { name: "West Garo Hills", totalCases: 210, urgentCases: 30, counsellors: 3, resolutionRate: 93, trend: "stable" },
    ],
  },
  mn: {
    id: "mn",
    code: "MN",
    name: "Manipur",
    capital: "Imphal",
    region: "North-East",
    riskLevel: "Moderate",
    nodalOfficer: "Smt. Ng. Uttam Singh, MCS (Social Welfare)",
    nodalPhone: "0385-2451810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 4,
    center: { x: 537, y: 301 },
    bounds: { minX: 519, maxX: 556, minY: 280, maxY: 323, width: 37, height: 43 },
    periods: {
      live: { totalCases: 8, urgentCases: 2, saathiCases: 2, helplineCalls: 20, resolutionRate: 85, avgResponseMins: 19 },
      week: { totalCases: 55, urgentCases: 9, saathiCases: 8, helplineCalls: 140, resolutionRate: 86, avgResponseMins: 22 },
      month: { totalCases: 220, urgentCases: 38, saathiCases: 34, helplineCalls: 560, resolutionRate: 88, avgResponseMins: 25 },
      annual: { totalCases: 1350, urgentCases: 240, saathiCases: 210, helplineCalls: 3450, resolutionRate: 89, avgResponseMins: 26 },
    },
    districts: [
      { name: "Imphal West", totalCases: 710, urgentCases: 120, counsellors: 6, resolutionRate: 91, trend: "down" },
      { name: "Churachandpur", totalCases: 390, urgentCases: 75, counsellors: 4, resolutionRate: 86, trend: "up" },
    ],
  },
  nl: {
    id: "nl",
    code: "NL",
    name: "Nagaland",
    capital: "Kohima",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Smt. Martha R. Ritse, IAS (Social Welfare)",
    nodalPhone: "0370-2271810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 546, y: 270 },
    bounds: { minX: 526, maxX: 566, minY: 248, maxY: 291, width: 40, height: 43 },
    periods: {
      live: { totalCases: 3, urgentCases: 0, saathiCases: 1, helplineCalls: 8, resolutionRate: 94, avgResponseMins: 14 },
      week: { totalCases: 20, urgentCases: 2, saathiCases: 4, helplineCalls: 55, resolutionRate: 95, avgResponseMins: 17 },
      month: { totalCases: 80, urgentCases: 8, saathiCases: 16, helplineCalls: 220, resolutionRate: 96, avgResponseMins: 19 },
      annual: { totalCases: 490, urgentCases: 55, saathiCases: 95, helplineCalls: 1350, resolutionRate: 96, avgResponseMins: 20 },
    },
    districts: [
      { name: "Kohima", totalCases: 280, urgentCases: 30, counsellors: 4, resolutionRate: 97, trend: "down" },
      { name: "Dimapur", totalCases: 160, urgentCases: 20, counsellors: 3, resolutionRate: 95, trend: "stable" },
    ],
  },
  mz: {
    id: "mz",
    code: "MZ",
    name: "Mizoram",
    capital: "Aizawl",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Smt. Lalzirmawii Chhangte, IAS (Social Welfare)",
    nodalPhone: "0389-2321810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 516, y: 337 },
    bounds: { minX: 504, maxX: 529, minY: 307, maxY: 366, width: 25, height: 59 },
    periods: {
      live: { totalCases: 2, urgentCases: 0, saathiCases: 1, helplineCalls: 6, resolutionRate: 95, avgResponseMins: 13 },
      week: { totalCases: 18, urgentCases: 2, saathiCases: 3, helplineCalls: 45, resolutionRate: 96, avgResponseMins: 16 },
      month: { totalCases: 70, urgentCases: 7, saathiCases: 14, helplineCalls: 180, resolutionRate: 97, avgResponseMins: 18 },
      annual: { totalCases: 440, urgentCases: 45, saathiCases: 85, helplineCalls: 1120, resolutionRate: 97, avgResponseMins: 19 },
    },
    districts: [
      { name: "Aizawl", totalCases: 290, urgentCases: 30, counsellors: 4, resolutionRate: 98, trend: "down" },
      { name: "Lunglei", totalCases: 110, urgentCases: 12, counsellors: 2, resolutionRate: 96, trend: "stable" },
    ],
  },
  ar: {
    id: "ar",
    code: "AR",
    name: "Arunachal Pradesh",
    capital: "Itanagar",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Smt. Nivedita Bhasin, IAS (WCD)",
    nodalPhone: "0360-2211810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 3,
    center: { x: 550, y: 224 },
    bounds: { minX: 489, maxX: 612, minY: 191, maxY: 258, width: 123, height: 67 },
    periods: {
      live: { totalCases: 3, urgentCases: 0, saathiCases: 1, helplineCalls: 8, resolutionRate: 93, avgResponseMins: 18 },
      week: { totalCases: 22, urgentCases: 3, saathiCases: 4, helplineCalls: 55, resolutionRate: 94, avgResponseMins: 22 },
      month: { totalCases: 90, urgentCases: 11, saathiCases: 18, helplineCalls: 220, resolutionRate: 95, avgResponseMins: 25 },
      annual: { totalCases: 540, urgentCases: 65, saathiCases: 105, helplineCalls: 1420, resolutionRate: 95, avgResponseMins: 26 },
    },
    districts: [
      { name: "Papum Pare (Itanagar)", totalCases: 310, urgentCases: 38, counsellors: 4, resolutionRate: 96, trend: "down" },
      { name: "Changlang", totalCases: 130, urgentCases: 16, counsellors: 2, resolutionRate: 94, trend: "stable" },
    ],
  },
  sk: {
    id: "sk",
    code: "SK",
    name: "Sikkim",
    capital: "Gangtok",
    region: "North-East",
    riskLevel: "Low",
    nodalOfficer: "Smt. Tashi Cho Cho, SCS (WCD)",
    nodalPhone: "03592-201810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 425, y: 235 },
    bounds: { minX: 415, maxX: 434, minY: 223, maxY: 248, width: 19, height: 25 },
    periods: {
      live: { totalCases: 1, urgentCases: 0, saathiCases: 1, helplineCalls: 4, resolutionRate: 96, avgResponseMins: 11 },
      week: { totalCases: 10, urgentCases: 1, saathiCases: 2, helplineCalls: 28, resolutionRate: 97, avgResponseMins: 14 },
      month: { totalCases: 45, urgentCases: 4, saathiCases: 8, helplineCalls: 110, resolutionRate: 98, avgResponseMins: 16 },
      annual: { totalCases: 270, urgentCases: 28, saathiCases: 55, helplineCalls: 720, resolutionRate: 98, avgResponseMins: 17 },
    },
    districts: [
      { name: "East Sikkim (Gangtok)", totalCases: 170, urgentCases: 18, counsellors: 3, resolutionRate: 98, trend: "down" },
      { name: "South Sikkim", totalCases: 65, urgentCases: 7, counsellors: 2, resolutionRate: 97, trend: "stable" },
    ],
  },
  ch: {
    id: "ch",
    code: "CH",
    name: "Chandigarh",
    capital: "Chandigarh",
    region: "North",
    riskLevel: "Low",
    nodalOfficer: "Shri Nitin Yadav, IAS (Social Welfare)",
    nodalPhone: "0172-2701810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 3,
    center: { x: 179, y: 160 },
    bounds: { minX: 178, maxX: 181, minY: 158, maxY: 162, width: 3, height: 3 },
    periods: {
      live: { totalCases: 3, urgentCases: 0, saathiCases: 1, helplineCalls: 8, resolutionRate: 96, avgResponseMins: 9 },
      week: { totalCases: 22, urgentCases: 2, saathiCases: 4, helplineCalls: 65, resolutionRate: 97, avgResponseMins: 11 },
      month: { totalCases: 95, urgentCases: 10, saathiCases: 18, helplineCalls: 260, resolutionRate: 98, avgResponseMins: 13 },
      annual: { totalCases: 580, urgentCases: 65, saathiCases: 115, helplineCalls: 1680, resolutionRate: 98, avgResponseMins: 14 },
    },
    districts: [
      { name: "Chandigarh City", totalCases: 580, urgentCases: 65, counsellors: 5, resolutionRate: 98, trend: "down" },
    ],
  },
  py: {
    id: "py",
    code: "PY",
    name: "Puducherry",
    capital: "Puducherry",
    region: "South",
    riskLevel: "Low",
    nodalOfficer: "Smt. P. Muthumeena, PCS (WCD)",
    nodalPhone: "0413-2241810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 268, y: 546 },
    bounds: { minX: 240, maxX: 295, minY: 481, maxY: 610, width: 56, height: 128 },
    periods: {
      live: { totalCases: 2, urgentCases: 0, saathiCases: 1, helplineCalls: 6, resolutionRate: 95, avgResponseMins: 11 },
      week: { totalCases: 16, urgentCases: 2, saathiCases: 3, helplineCalls: 48, resolutionRate: 96, avgResponseMins: 14 },
      month: { totalCases: 65, urgentCases: 7, saathiCases: 12, helplineCalls: 195, resolutionRate: 97, avgResponseMins: 16 },
      annual: { totalCases: 390, urgentCases: 42, saathiCases: 80, helplineCalls: 1240, resolutionRate: 97, avgResponseMins: 17 },
    },
    districts: [
      { name: "Puducherry", totalCases: 260, urgentCases: 28, counsellors: 3, resolutionRate: 98, trend: "down" },
      { name: "Karaikal", totalCases: 85, urgentCases: 9, counsellors: 2, resolutionRate: 96, trend: "stable" },
    ],
  },
  an: {
    id: "an",
    code: "AN",
    name: "Andaman and Nicobar Islands",
    capital: "Port Blair",
    region: "Islands",
    riskLevel: "Low",
    nodalOfficer: "Dr. Nitin Shakya (Director SW)",
    nodalPhone: "03192-232181 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 521, y: 609 },
    bounds: { minX: 503, maxX: 539, minY: 522, maxY: 696, width: 36, height: 174 },
    periods: {
      live: { totalCases: 1, urgentCases: 0, saathiCases: 1, helplineCalls: 3, resolutionRate: 95, avgResponseMins: 14 },
      week: { totalCases: 8, urgentCases: 1, saathiCases: 2, helplineCalls: 24, resolutionRate: 96, avgResponseMins: 17 },
      month: { totalCases: 35, urgentCases: 4, saathiCases: 8, helplineCalls: 98, resolutionRate: 97, avgResponseMins: 20 },
      annual: { totalCases: 210, urgentCases: 24, saathiCases: 48, helplineCalls: 620, resolutionRate: 97, avgResponseMins: 21 },
    },
    districts: [
      { name: "South Andaman (Port Blair)", totalCases: 140, urgentCases: 16, counsellors: 3, resolutionRate: 98, trend: "down" },
      { name: "North & Middle Andaman", totalCases: 55, urgentCases: 6, counsellors: 2, resolutionRate: 96, trend: "stable" },
    ],
  },
  ld: {
    id: "ld",
    code: "LD",
    name: "Lakshadweep",
    capital: "Kavaratti",
    region: "Islands",
    riskLevel: "Low",
    nodalOfficer: "Shri S. Asker Ali, IAS (WCD)",
    nodalPhone: "04896-262181 / 181",
    helpline181Active: true,
    activeFlyingSquads: 1,
    center: { x: 99, y: 627 },
    bounds: { minX: 82, maxX: 116, minY: 591, maxY: 664, width: 34, height: 73 },
    periods: {
      live: { totalCases: 0, urgentCases: 0, saathiCases: 0, helplineCalls: 1, resolutionRate: 98, avgResponseMins: 12 },
      week: { totalCases: 2, urgentCases: 0, saathiCases: 1, helplineCalls: 6, resolutionRate: 98, avgResponseMins: 15 },
      month: { totalCases: 8, urgentCases: 1, saathiCases: 3, helplineCalls: 22, resolutionRate: 98, avgResponseMins: 17 },
      annual: { totalCases: 50, urgentCases: 5, saathiCases: 18, helplineCalls: 140, resolutionRate: 99, avgResponseMins: 18 },
    },
    districts: [
      { name: "Kavaratti", totalCases: 35, urgentCases: 3, counsellors: 2, resolutionRate: 99, trend: "stable" },
    ],
  },
  dn: {
    id: "dn",
    code: "DN",
    name: "Dadra and Nagar Haveli",
    capital: "Silvassa",
    region: "West",
    riskLevel: "Low",
    nodalOfficer: "Smt. Pooja Jain, IAS (Social Welfare)",
    nodalPhone: "0260-2641810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 102, y: 405 },
    bounds: { minX: 99, maxX: 106, minY: 402, maxY: 408, width: 6, height: 7 },
    periods: {
      live: { totalCases: 1, urgentCases: 0, saathiCases: 1, helplineCalls: 3, resolutionRate: 94, avgResponseMins: 12 },
      week: { totalCases: 7, urgentCases: 1, saathiCases: 2, helplineCalls: 22, resolutionRate: 95, avgResponseMins: 15 },
      month: { totalCases: 30, urgentCases: 3, saathiCases: 7, helplineCalls: 88, resolutionRate: 96, avgResponseMins: 17 },
      annual: { totalCases: 180, urgentCases: 20, saathiCases: 42, helplineCalls: 560, resolutionRate: 96, avgResponseMins: 18 },
    },
    districts: [
      { name: "Dadra and Nagar Haveli", totalCases: 180, urgentCases: 20, counsellors: 3, resolutionRate: 96, trend: "stable" },
    ],
  },
  dd: {
    id: "dd",
    code: "DD",
    name: "Daman and Diu",
    capital: "Daman",
    region: "West",
    riskLevel: "Low",
    nodalOfficer: "Smt. Saloni Rai, IAS (WCD)",
    nodalPhone: "0260-2231810 / 181",
    helpline181Active: true,
    activeFlyingSquads: 2,
    center: { x: 54, y: 391 },
    bounds: { minX: 52, maxX: 57, minY: 387, maxY: 394, width: 5, height: 7 },
    periods: {
      live: { totalCases: 1, urgentCases: 0, saathiCases: 1, helplineCalls: 3, resolutionRate: 95, avgResponseMins: 11 },
      week: { totalCases: 6, urgentCases: 1, saathiCases: 2, helplineCalls: 20, resolutionRate: 96, avgResponseMins: 14 },
      month: { totalCases: 25, urgentCases: 3, saathiCases: 6, helplineCalls: 75, resolutionRate: 97, avgResponseMins: 16 },
      annual: { totalCases: 150, urgentCases: 16, saathiCases: 38, helplineCalls: 480, resolutionRate: 97, avgResponseMins: 17 },
    },
    districts: [
      { name: "Daman", totalCases: 100, urgentCases: 11, counsellors: 2, resolutionRate: 97, trend: "down" },
      { name: "Diu", totalCases: 50, urgentCases: 5, counsellors: 1, resolutionRate: 98, trend: "stable" },
    ],
  },
};

// Combine SVG path contours from @svg-maps/india with rich analytical metadata
export type MapStateFeature = DetailedStateData & {
  pathD: string;
};

export const allIndiaFeatures: MapStateFeature[] = (indiaSvgMap.locations as { id: string; name: string; path: string }[]).map((loc) => {
  const meta = detailedStatesMap[loc.id.toLowerCase()];
  if (!meta) {
    return {
      id: loc.id.toLowerCase(),
      code: loc.id.toUpperCase(),
      name: loc.name,
      capital: "State HQ",
      region: "Central",
      riskLevel: "Low",
      nodalOfficer: "State Nodal Cell",
      nodalPhone: "181",
      helpline181Active: true,
      activeFlyingSquads: 2,
      center: { x: 300, y: 300 },
      bounds: { minX: 200, maxX: 400, minY: 200, maxY: 400, width: 200, height: 200 },
      periods: {
        live: { totalCases: 10, urgentCases: 1, saathiCases: 2, helplineCalls: 20, resolutionRate: 90, avgResponseMins: 15 },
        week: { totalCases: 70, urgentCases: 8, saathiCases: 15, helplineCalls: 140, resolutionRate: 92, avgResponseMins: 18 },
        month: { totalCases: 300, urgentCases: 35, saathiCases: 60, helplineCalls: 600, resolutionRate: 94, avgResponseMins: 20 },
        annual: { totalCases: 1800, urgentCases: 210, saathiCases: 360, helplineCalls: 3600, resolutionRate: 95, avgResponseMins: 22 },
      },
      districts: [{ name: "District 1", totalCases: 1800, urgentCases: 210, counsellors: 4, resolutionRate: 95, trend: "stable" }],
      pathD: loc.path,
    };
  }
  return {
    ...meta,
    pathD: loc.path,
  };
});
