/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as CounsellorRouteImport } from './routes/counsellor'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as VictimRouteImport } from './routes/victim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorRoute = CounsellorRouteImport.update({
  id: '/counsellor',
  path: '/counsellor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const VictimRoute = VictimRouteImport.update({
  id: '/victim',
  path: '/victim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/counsellor': typeof CounsellorRoute
  '/supervisor': typeof SupervisorRoute
  '/victim': typeof VictimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/counsellor': typeof CounsellorRoute
  '/supervisor': typeof SupervisorRoute
  '/victim': typeof VictimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/counsellor': typeof CounsellorRoute
  '/supervisor': typeof SupervisorRoute
  '/victim': typeof VictimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caregiver' | '/counsellor' | '/supervisor' | '/victim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caregiver' | '/counsellor' | '/supervisor' | '/victim'
  id:
    '__root__' | '/' | '/caregiver' | '/counsellor' | '/supervisor' | '/victim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverRoute: typeof CaregiverRoute
  CounsellorRoute: typeof CounsellorRoute
  SupervisorRoute: typeof SupervisorRoute
  VictimRoute: typeof VictimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor': {
      id: '/counsellor'
      path: '/counsellor'
      fullPath: '/counsellor'
      preLoaderRoute: typeof CounsellorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/victim': {
      id: '/victim'
      path: '/victim'
      fullPath: '/victim'
      preLoaderRoute: typeof VictimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverRoute: CaregiverRoute,
  CounsellorRoute: CounsellorRoute,
  SupervisorRoute: SupervisorRoute,
  VictimRoute: VictimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
